"""empty message

Revision ID: e95632cbcc6d
Revises: 
Create Date: 2020-01-11 11:39:02.662502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95632cbcc6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('platform_build_version_code', sa.String(), nullable=True),
    sa.Column('platform_build_version_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package')
    )
    op.create_table('asns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asns_app_id'), 'asns', ['app_id'], unique=False)
    op.create_table('attacktactics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('attack_tactic', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacktactics_app_id'), 'attacktactics', ['app_id'], unique=False)
    op.create_table('attacktechniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('attach_techniques', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacktechniques_app_id'), 'attacktechniques', ['app_id'], unique=False)
    op.create_table('bitcoinaddresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('bitcoin_address', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitcoinaddresses_app_id'), 'bitcoinaddresses', ['app_id'], unique=False)
    op.create_table('creditcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditcards_app_id'), 'creditcards', ['app_id'], unique=False)
    op.create_table('cves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('cve', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cves_app_id'), 'cves', ['app_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_app_id'), 'domains', ['app_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_app_id'), 'emails', ['app_id'], unique=False)
    op.create_table('googleadsense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('adsense_id', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_googleadsense_app_id'), 'googleadsense', ['app_id'], unique=False)
    op.create_table('googleanalytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('analytic_id', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_googleanalytics_app_id'), 'googleanalytics', ['app_id'], unique=False)
    op.create_table('hashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('hash_type', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashes_app_id'), 'hashes', ['app_id'], unique=False)
    op.create_table('ipblocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('ip_block', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipblocks_app_id'), 'ipblocks', ['app_id'], unique=False)
    op.create_table('ipv4s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('asn_name', sa.String(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipv4s_app_id'), 'ipv4s', ['app_id'], unique=False)
    op.create_table('ipv6s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipv6s_app_id'), 'ipv6s', ['app_id'], unique=False)
    op.create_table('macaddresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('macaddress', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macaddresses_app_id'), 'macaddresses', ['app_id'], unique=False)
    op.create_table('phonenumbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phonenumbers_app_id'), 'phonenumbers', ['app_id'], unique=False)
    op.create_table('tckns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('tckn', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tckns_app_id'), 'tckns', ['app_id'], unique=False)
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_app_id'), 'urls', ['app_id'], unique=False)
    op.create_table('useragents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useragents_app_id'), 'useragents', ['app_id'], unique=False)
    op.create_table('xmppaccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('xmpp_account', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xmppaccounts_app_id'), 'xmppaccounts', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xmppaccounts_app_id'), table_name='xmppaccounts')
    op.drop_table('xmppaccounts')
    op.drop_index(op.f('ix_useragents_app_id'), table_name='useragents')
    op.drop_table('useragents')
    op.drop_index(op.f('ix_urls_app_id'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_tckns_app_id'), table_name='tckns')
    op.drop_table('tckns')
    op.drop_index(op.f('ix_phonenumbers_app_id'), table_name='phonenumbers')
    op.drop_table('phonenumbers')
    op.drop_index(op.f('ix_macaddresses_app_id'), table_name='macaddresses')
    op.drop_table('macaddresses')
    op.drop_index(op.f('ix_ipv6s_app_id'), table_name='ipv6s')
    op.drop_table('ipv6s')
    op.drop_index(op.f('ix_ipv4s_app_id'), table_name='ipv4s')
    op.drop_table('ipv4s')
    op.drop_index(op.f('ix_ipblocks_app_id'), table_name='ipblocks')
    op.drop_table('ipblocks')
    op.drop_index(op.f('ix_hashes_app_id'), table_name='hashes')
    op.drop_table('hashes')
    op.drop_index(op.f('ix_googleanalytics_app_id'), table_name='googleanalytics')
    op.drop_table('googleanalytics')
    op.drop_index(op.f('ix_googleadsense_app_id'), table_name='googleadsense')
    op.drop_table('googleadsense')
    op.drop_index(op.f('ix_emails_app_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_domains_app_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_cves_app_id'), table_name='cves')
    op.drop_table('cves')
    op.drop_index(op.f('ix_creditcards_app_id'), table_name='creditcards')
    op.drop_table('creditcards')
    op.drop_index(op.f('ix_bitcoinaddresses_app_id'), table_name='bitcoinaddresses')
    op.drop_table('bitcoinaddresses')
    op.drop_index(op.f('ix_attacktechniques_app_id'), table_name='attacktechniques')
    op.drop_table('attacktechniques')
    op.drop_index(op.f('ix_attacktactics_app_id'), table_name='attacktactics')
    op.drop_table('attacktactics')
    op.drop_index(op.f('ix_asns_app_id'), table_name='asns')
    op.drop_table('asns')
    op.drop_table('apps')
    # ### end Alembic commands ###
